[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = part.csv
board_build.filesystem = littlefs

extra_scripts = pre:extra_scripts/set_version.py

; ==== FLAGS REQUIS POUR L'ESP32-C3 SUPER MINI ====
; Active le port USB natif pour que Serial.print fonctionne correctement
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_compat_mode = strict
lib_deps =
    olikraus/U8g2@^2.34.22
    ayushsharma82/ElegantOTA@^3.1.7
    